# Generated by Django 3.1.5 on 2021-01-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210122_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='small_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
