# Generated by Django 3.1.5 on 2021-01-27 16:32

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_small_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(upload_to=courses.models.get_course_upload_directory),
        ),
        migrations.AlterField(
            model_name='course',
            name='small_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.get_course_upload_directory),
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sections', to='courses.course')),
            ],
            options={
                'order_with_respect_to': 'course',
            },
        ),
    ]
