# Generated by Django 3.2.6 on 2021-12-03 20:16
from uuid import uuid4
from django.db import migrations, models


def add_file_uuids(apps, schema_editor):
    Courses = apps.get_model("courses", "Course")
    updated_courses = []
    for course in Courses.objects.all():
        course.file_uuid = uuid4()
        updated_courses.append(course)
    Courses.objects.bulk_update(updated_courses, ["file_uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_coursesignup"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="file_uuid",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.RunPython(add_file_uuids, migrations.RunPython.noop)
    ]
