# Generated by Django 3.2.6 on 2021-12-03 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_file_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='file_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
