version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - pip install docker-compose
  pre_build:
    commands:
      - cp .env.example .env
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker-compose build web
  build:
    commands:
      - docker-compose run web python manage.py test
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 941606308749.dkr.ecr.eu-central-1.amazonaws.com
      - docker build -f docker/Dockerfile -t blacksheeplearns .
      - docker tag blacksheeplearns:latest 941606308749.dkr.ecr.eu-central-1.amazonaws.com/blacksheeplearns:latest
      - docker push 941606308749.dkr.ecr.eu-central-1.amazonaws.com/blacksheeplearns:latest
  post_build:
    commands:
      - docker-compose down

artifacts:
    files:
        - imagedefinitions.json
