version: "3.8"

services:
  db:
    image: postgres:12-alpine
    env_file:
      .env
    ports:
      - "5432:5432"
    volumes:
      - learn-web-dev-data:/var/lib/postgresql/data
  web:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      .env
    volumes:
      - ./src/:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis:6.0-alpine
    ports:
      - "6379:6379"
  celery:
    build:
      dockerfile: docker/Dockerfile
      context: .
    env_file:
      .env
    command: celery -A settings worker
    volumes:
      - ./src/:/app/
    depends_on:
      - redis
volumes:
  learn-web-dev-data:
