version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.9
        auth:
          username: gonczor
          password: $DOCKERHUB_TOKEN
      - image: circleci/postgres:12
        auth:
          username: gonczor
          password: $DOCKERHUB_TOKEN
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
    steps:
      - checkout
      - run: docker-compose run web test

workflows:
  main:
    jobs:
      - test
